добавлена функция отсчета времени от текущего времени до завтра и его…
makehtml/yeticave pull request #4
Opened 2019-06-01 17:23 UTC by ChloeSilent

… вывод в карточки лотов. Попытка добавить таймзону

2019-06-02 02:31 UTC, ademaro requested changes
Давай доработаем и двинем дальше...

2019-06-02 02:31 UTC, ademaro commented on functions.php
> + * @return {array} массив с 2мя ключами, значение первого - остав часы, второго - остав минуты
а почему ты сразу в нормальном формате не хочешь выводить? почему массив?)

2019-06-02 02:31 UTC, ademaro commented on index.php
> +    "remain_hours" => cout_time ($today, $tomorrow)[0],
тут массив вообще не читаем...

2019-06-02 02:31 UTC, ademaro commented on templates/index.php
> +                                <?= $remain_hours ?>:<?= $remain_min ?>
Выводи из ф-ции строку... И вообще, тебе надо запускать эту ф-цию _для каждой задачи_, а не считать один раз для всех. Давай перенесём вызов ф-ции в нужное место.

2019-06-02 16:16 UTC, ChloeSilent commented on functions.php
> + * @return {array} массив с 2мя ключами, значение первого - остав часы, второго - остав минуты
Так норм будет?
return "$remain_hours:$remain_min";

2019-06-02 16:16 UTC, ChloeSilent commented on functions.php
> + * @return {array} массив с 2мя ключами, значение первого - остав часы, второго - остав минуты
* @return {string}  с 2мя значениями, разделенным двоеточием, значение первого - остав часы, второго - остав минуты

2019-06-02 16:19 UTC, ademaro commented on functions.php
> + * @return {array} массив с 2мя ключами, значение первого - остав часы, второго - остав минуты
почитай ещё про https://www.php.net/manual/ru/function.date.php и https://www.php.net/manual/ru/datetime.format.php

2019-06-02 16:26 UTC, ChloeSilent commented on index.php
> +    "remain_hours" => cout_time ($today, $tomorrow)[0],
Поменяла на     "remain" => cout_time ($today, $tomorrow). 
А что значит не читае

2019-06-06 08:44 UTC, ademaro approved these changes
Давай пока закроем, что бы двигать дальше, пока норм, но хорошо бы улучшить...

2019-06-06 08:44 UTC, ademaro commented on templates/config.php
> +date.timezone = America/Los_Angeles;
https://www.php.net/manual/ru/function.date-default-timezone-set.php посмотри как правильно определяется зона

2019-06-06 08:44 UTC, ademaro commented on functions.php
> +return "$remain_hours:$remain_min";
немного костыльно, ты читала что можно сразу как надо выводить? https://www.php.net/manual/ru/function.date.php

2019-06-06 08:44 UTC, merged